version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"

  app:
    build: .
    depends_on:
      - mysql
    environment:
      MYSQL_DB_URL: jdbc:mysql://mysql:3306/test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: root
    ports:
      - "8080:8080"
