server:
  port: 8080

# jdbc and jpa config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: UTC

  # Mail Config
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          timeout: '5000'
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
    host: smtp.gmail.com
    username: <<YOUR GMAIL>>
    password: <<Generate-App-password-for-gmail>> # Google Account, Search "App Passwords", generate password
    port: '587'

  # freemarker config - used for email templates
  freemarker:
    template-loader-path: classpath:/mail-templates
    suffix: .ftl

  # Spring security oauth2 config
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <<ClientID>>
            clientSecret: <<ClientSecret>>
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: email, profile

          facebook:
            clientId: <<ClientID>>
            clientSecret: <<ClientSecret>>
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: email, public_profile

          github:
            clientId: <<ClientID>>
            clientSecret: <<ClientSecret>>
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: user, user:email


# logging config
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG


# App Custom Properties
myapp:

  appName: spring security OAuth2 and JWT starter example
  officialCompanyName: XYZ-Company Inc.
  officialCompanyDomain: http://localhost:4200

  mail:
    defaultEmailAddress: example@gmail.com
    verificationCodeExpirationSeconds: 1800 # 30 minutes

  jwt:
    privateKey: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDyUlWEzPJPVesj
      XUnd/X68XpF/r7ZXqWTbK0kwQrnICZIC73vDO+Zl0b6YggXJaB6WcBeopbU67I8N
      snW1dAnz7sxNqit3/HHvmRZvgTfvqJ0WaTPhS2TuekZDRURLl9rbxSCDoh7y3rrz
      OI/Wm5bsrEqEY2jegr0poP8zFcLf31ggUIVchgMDGqcJBWhJmF8DJ8qoo6chjlZF
      oRrdibbQ6rKRc7y5SBorNOEL/eU70L4V0LYvQTwyfbFOIvNCj7101cQ+byNDMytn
      8wZ7DUNV4Vteu/G+qYlmhflkrFOf9s3xpJ8D/7nK5AIbMWAcbktrW0ZcrM7aRYWG
      8HoV43L7AgMBAAECggEASo5SiZ2VIBvLUQIu7AJGsCZYlfS2IZqY0WYsCpE9H/Lx
      3b1ZUuRnKwSxo7K9nQ5P+vFaFiWF8S8/hHNYDBA7z7W1Xl/xJ+WgGJv9bylO0IoM
      awzLTZIo58bvP1tce/Wo/N1V96o143vsAVFx0BHnCcKo2rrLVUrccKZ8XndfkglI
      jC2r3pqJAno8R2U5HBKbLhnLk3AxwwCJAQn3EAiE9wNR4qhlPSZNG2qOEjuQO9hd
      eedWXv0h++8/kiY3+mZF0wPkdnLgS0/3lVEDn0nyn9cG/4A/neG7ju7VTe6pKlXa
      VAzGMfcx6g+YI31otCjg2GgaZPbLfk2nmtGWUWrDQQKBgQD5Yc3NQR8NB1y8R1Xz
      QbitCqYGmB13bEXxf9/ohicJVE3tjQZTa9Dy2XqFYhiFT2UcDwS7/yjRt6a5QV96
      Bw5rPxMAamDPvz+4tpMx74wCa37SzOTcsRKw45t2B6GGelhduRGnjAuBnzNVfdpf
      SG+gbcwLIAu2O09f2polaAKBQwKBgQD4wJCIHPIp3w8Iv7yNivMnoJaQ2+pQ+0i/
      wbR/3MyZe+XV9DLO86KYfnj7EDRC1QBpecKuL6UF9zFrt5Oowg2VIFvvUfTzTbX2
      j79+nYNcuOaV5MeAvO2D2MK/IEEzt5VW9RgXu219+200rOkn6VrGzbWWlTtE8Olg
      UnxnblWv6QKBgQDRKi8rUMtyahJl+I8mkKEMwjmunjdYyv9/JvnuVVa4hHU4IWiE
      35FJnw8cgMKATa9IcXBPHhxmidrU1vf1qaV2XljZqF+633Xav4eGAp00CmU8+Y2b
      bQl4Q+9Id+4KlOM4+NjN5rBf799mfUCDWoYF0RGq4x3vop9YjklrxmkTcQKBgENk
      EAQAK48yciVBpLiIC2YR+JiYK7vyx/vDY748OGXgjhzPwrAUi1la8jW6Zx4wDKOG
      rDp6h++8z3PKUUOoBvv+v0lv37fGtuRsf0mzLLKDGV1ElNQI2yQcJm6XM3Lqapgb
      YIKVcY1u/2AE9Emuy7wOYQLBvUPpLKC+2BtBZg95AoGAPq7tut87KrTczGDcee78
      aqAN4tuEvlm6F1NHEIOXpSRVnVCOBgTdG8W4rqI4CMTlseghhUZ8c8DpMtTF4ZlM
      jANHIVsqrKnjmy9JK4MvHh/IixGsNU7uIRgH9kyKkpQioo9zhLCJDs0q1Qhh0SnD
      s//MBj6+zGjXxE9JbFbge+w=
      -----END PRIVATE KEY-----
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8lJVhMzyT1XrI11J3f1+
      vF6Rf6+2V6lk2ytJMEK5yAmSAu97wzvmZdG+mIIFyWgelnAXqKW1OuyPDbJ1tXQJ
      8+7MTaord/xx75kWb4E376idFmkz4Utk7npGQ0VES5fa28Ugg6Ie8t668ziP1puW
      7KxKhGNo3oK9KaD/MxXC399YIFCFXIYDAxqnCQVoSZhfAyfKqKOnIY5WRaEa3Ym2
      0OqykXO8uUgaKzThC/3lO9C+FdC2L0E8Mn2xTiLzQo+9dNXEPm8jQzMrZ/MGew1D
      VeFbXrvxvqmJZoX5ZKxTn/bN8aSfA/+5yuQCGzFgHG5La1tGXKzO2kWFhvB6FeNy
      +wIDAQAB
      -----END PUBLIC KEY-----
    expirationMillis: 3600000
    shortLivedMillis: 120000

  cors:
    allowedOrigins: http://localhost:8080,http://localhost:4200

  oauth2:
    authorizedRedirectOrigins: http://localhost:8080,http://localhost:4200
    cookieExpireSeconds: 120

  defaults:
    defaultPageStart: 0
    defaultPageSize: 50
